const fs = require("fs");
const path = require("path");
const { spawn } = require("child_process");
const { safeFileName } = require("./utils");

function runYtDlp({ ytDlpBin, ffmpegBin, url, mode, outputDir }) {
  return new Promise((resolve, reject) => {
    const fileTag = Date.now().toString();
    const outTemplate = path.join(outputDir, `${fileTag}_%(title).50s.%(ext)s`);

    const ffmpegRaw = String(ffmpegBin || "").trim();
    const ffmpegResolved = ffmpegRaw
      ? path.resolve(process.cwd(), ffmpegRaw)
      : "";
    const ffmpegLocation = fs.existsSync(ffmpegRaw)
      ? ffmpegRaw
      : ffmpegResolved && fs.existsSync(ffmpegResolved)
        ? ffmpegResolved
        : "";

    const args = [
      "--no-playlist",
      "--restrict-filenames",
      "--js-runtimes",
      "node",
    ];

    if (ffmpegLocation) {
      args.push("--ffmpeg-location", ffmpegLocation);
    }

    args.push("-o", outTemplate);

    if (mode === "audio") {
      args.push("-x", "--audio-format", "mp3");
    } else {
      args.push("-f", "mp4/best");
    }

    args.push(url);

    const child = spawn(ytDlpBin, args, {
      windowsHide: true,
    });

    let stdErr = "";

    child.stderr.on("data", (chunk) => {
      stdErr += chunk.toString();
    });

    child.on("error", (error) => {
      reject(error);
    });

    child.on("close", (code) => {
      if (code !== 0) {
        reject(new Error(`yt-dlp exited with code ${code}: ${stdErr}`));
        return;
      }

      const files = fs
        .readdirSync(outputDir)
        .map((name) => path.join(outputDir, name))
        .filter((filePath) => fs.statSync(filePath).isFile())
        .sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs);

      if (!files.length) {
        reject(new Error("No file generated by yt-dlp"));
        return;
      }

      const latestFile = files[0];
      resolve(latestFile);
    });
  });
}

function getYtDlpTitle({ ytDlpBin, url }) {
  return new Promise((resolve) => {
    const args = [
      "--no-playlist",
      "--no-warnings",
      "--skip-download",
      "--js-runtimes",
      "node",
      "--print",
      "%(title)s",
      url,
    ];

    const child = spawn(ytDlpBin, args, {
      windowsHide: true,
    });

    let stdOut = "";

    child.stdout.on("data", (chunk) => {
      stdOut += chunk.toString();
    });

    child.on("error", () => {
      resolve(null);
    });

    child.on("close", (code) => {
      if (code !== 0) {
        resolve(null);
        return;
      }

      const title = stdOut
        .split(/\r?\n/g)
        .map((line) => line.trim())
        .find(Boolean);

      resolve(title || null);
    });
  });
}

function getMediaType(mode) {
  if (mode === "audio") {
    return {
      messageType: "audio",
      mimetype: "audio/mpeg",
    };
  }

  return {
    messageType: "video",
    mimetype: "video/mp4",
  };
}

function normalizeMode(value) {
  return String(value || "video").toLowerCase() === "audio" ? "audio" : "video";
}

function readableSize(bytes) {
  if (!Number.isFinite(bytes) || bytes < 0) {
    return "0 B";
  }

  const units = ["B", "KB", "MB", "GB"];
  let size = bytes;
  let i = 0;

  while (size >= 1024 && i < units.length - 1) {
    size /= 1024;
    i += 1;
  }

  return `${size.toFixed(i === 0 ? 0 : 2)} ${units[i]}`;
}

function makeOutputFileName(baseName, mode) {
  const ext = mode === "audio" ? ".mp3" : ".mp4";
  const safe = safeFileName(baseName || "media");
  return `${safe}${ext}`;
}

function extractMediaTitle(filePathOrBaseName) {
  const rawBaseName = path.basename(
    String(filePathOrBaseName || ""),
    path.extname(String(filePathOrBaseName || "")),
  );

  const withoutTag = rawBaseName.replace(/^\d+_/, "");
  const readable = withoutTag
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  return readable || "media";
}

module.exports = {
  runYtDlp,
  getYtDlpTitle,
  getMediaType,
  normalizeMode,
  readableSize,
  makeOutputFileName,
  extractMediaTitle,
};
