const fs = require("fs");
const path = require("path");
const { spawn } = require("child_process");
const { safeFileName } = require("./utils");

function resolveExistingPath(rawPath) {
  const value = String(rawPath || "").trim();
  if (!value) {
    return "";
  }

  const absolutePath = path.resolve(process.cwd(), value);
  if (fs.existsSync(value)) {
    return value;
  }

  if (fs.existsSync(absolutePath)) {
    return absolutePath;
  }

  return "";
}

function getYtDlpCommonArgs({
  ffmpegBin,
  ytDlpCookiesFile,
  ytDlpCookiesFromBrowser,
}) {
  const args = [
    "--no-playlist",
    "--restrict-filenames",
    "--js-runtimes",
    "node",
  ];

  const ffmpegLocation = resolveExistingPath(ffmpegBin);
  if (ffmpegLocation) {
    args.push("--ffmpeg-location", ffmpegLocation);
  }

  const cookiesFileRaw = String(ytDlpCookiesFile || "").trim();
  const cookiesFile = resolveExistingPath(cookiesFileRaw);
  const cookiesFromBrowser = String(ytDlpCookiesFromBrowser || "").trim();

  if (cookiesFileRaw && !cookiesFile) {
    throw new Error(`Configured ytDlpCookiesFile not found: ${cookiesFileRaw}`);
  }

  if (cookiesFile) {
    args.push("--cookies", cookiesFile);
  } else if (cookiesFromBrowser) {
    args.push("--cookies-from-browser", cookiesFromBrowser);
  }

  return args;
}

function isYtAuthChallengeError(message) {
  const text = String(message || "").toLowerCase();
  return text.includes("sign in to confirm you're not a bot");
}

function isBrowserCookieDecryptError(message) {
  const text = String(message || "").toLowerCase();
  return (
    text.includes("failed to decrypt with dpapi") ||
    text.includes("attributerror") ||
    text.includes("nonetype")
  );
}

function getDownloaderUserFacingError(error) {
  const raw = String(error?.message || "");
  const lower = raw.toLowerCase();

  if (lower.includes("configured ytdlpcookiesfile not found")) {
    return [
      "File cookie tidak ditemukan sesuai config ytDlpCookiesFile.",
      "Pastikan file ada di path yang sama persis dengan nilai di config.",
      "Contoh: ytDlpCookiesFile = ./cookies.txt jika file ada di root project.",
    ].join("\n");
  }

  if (isYtAuthChallengeError(raw)) {
    return [
      "YouTube meminta verifikasi login (anti-bot).",
      "Solusi: isi config ytDlpCookiesFile dengan file cookies.txt yang valid.",
      "Jika memakai ytDlpCookiesFromBrowser, pastikan browser ditutup saat yt-dlp membaca cookie.",
    ].join("\n");
  }

  if (isBrowserCookieDecryptError(raw)) {
    return [
      "yt-dlp gagal membaca cookie browser (DPAPI/decrypt).",
      "Solusi paling stabil: export cookie ke cookies.txt lalu pakai ytDlpCookiesFile.",
      "Jika tetap pakai ytDlpCookiesFromBrowser, jalankan bot dengan user Windows yang sama dan tutup browser saat proses download.",
    ].join("\n");
  }

  return null;
}

function runYtDlp({
  ytDlpBin,
  ffmpegBin,
  ytDlpCookiesFile,
  ytDlpCookiesFromBrowser,
  url,
  mode,
  outputDir,
}) {
  return new Promise((resolve, reject) => {
    const fileTag = Date.now().toString();
    const outTemplate = path.join(outputDir, `${fileTag}_%(title).50s.%(ext)s`);

    const args = getYtDlpCommonArgs({
      ffmpegBin,
      ytDlpCookiesFile,
      ytDlpCookiesFromBrowser,
    });

    args.push("-o", outTemplate);

    if (mode === "audio") {
      args.push("-x", "--audio-format", "mp3");
    } else {
      args.push("-f", "mp4/best");
    }

    args.push(url);

    const child = spawn(ytDlpBin, args, {
      windowsHide: true,
    });

    let stdErr = "";

    child.stderr.on("data", (chunk) => {
      stdErr += chunk.toString();
    });

    child.on("error", (error) => {
      reject(error);
    });

    child.on("close", (code) => {
      if (code !== 0) {
        reject(new Error(`yt-dlp exited with code ${code}: ${stdErr}`));
        return;
      }

      const files = fs
        .readdirSync(outputDir)
        .map((name) => path.join(outputDir, name))
        .filter((filePath) => fs.statSync(filePath).isFile())
        .sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs);

      if (!files.length) {
        reject(new Error("No file generated by yt-dlp"));
        return;
      }

      const latestFile = files[0];
      resolve(latestFile);
    });
  });
}

function getYtDlpTitle({
  ytDlpBin,
  ffmpegBin,
  ytDlpCookiesFile,
  ytDlpCookiesFromBrowser,
  url,
}) {
  return new Promise((resolve) => {
    const args = getYtDlpCommonArgs({
      ffmpegBin,
      ytDlpCookiesFile,
      ytDlpCookiesFromBrowser,
    });

    args.push("--no-warnings", "--skip-download", "--print", "%(title)s", url);

    const child = spawn(ytDlpBin, args, {
      windowsHide: true,
    });

    let stdOut = "";

    child.stdout.on("data", (chunk) => {
      stdOut += chunk.toString();
    });

    child.on("error", () => {
      resolve(null);
    });

    child.on("close", (code) => {
      if (code !== 0) {
        resolve(null);
        return;
      }

      const title = stdOut
        .split(/\r?\n/g)
        .map((line) => line.trim())
        .find(Boolean);

      resolve(title || null);
    });
  });
}

function getYtDlpInfo({
  ytDlpBin,
  ffmpegBin,
  ytDlpCookiesFile,
  ytDlpCookiesFromBrowser,
  url,
}) {
  return new Promise((resolve, reject) => {
    const args = getYtDlpCommonArgs({
      ffmpegBin,
      ytDlpCookiesFile,
      ytDlpCookiesFromBrowser,
    });

    args.push("--no-warnings", "--skip-download", "--dump-single-json", url);

    const child = spawn(ytDlpBin, args, {
      windowsHide: true,
    });

    let stdOut = "";
    let stdErr = "";

    child.stdout.on("data", (chunk) => {
      stdOut += chunk.toString();
    });

    child.stderr.on("data", (chunk) => {
      stdErr += chunk.toString();
    });

    child.on("error", (error) => {
      reject(error);
    });

    child.on("close", (code) => {
      if (code !== 0) {
        reject(new Error(`yt-dlp info exited with code ${code}: ${stdErr}`));
        return;
      }

      try {
        const parsed = JSON.parse(stdOut);
        resolve(parsed);
      } catch (error) {
        reject(new Error(`Failed parsing yt-dlp info JSON: ${error.message}`));
      }
    });
  });
}

function getMediaType(mode) {
  if (mode === "audio") {
    return {
      messageType: "audio",
      mimetype: "audio/mpeg",
    };
  }

  return {
    messageType: "video",
    mimetype: "video/mp4",
  };
}

function normalizeMode(value) {
  return String(value || "video").toLowerCase() === "audio" ? "audio" : "video";
}

function readableSize(bytes) {
  if (!Number.isFinite(bytes) || bytes < 0) {
    return "0 B";
  }

  const units = ["B", "KB", "MB", "GB"];
  let size = bytes;
  let i = 0;

  while (size >= 1024 && i < units.length - 1) {
    size /= 1024;
    i += 1;
  }

  return `${size.toFixed(i === 0 ? 0 : 2)} ${units[i]}`;
}

function makeOutputFileName(baseName, mode) {
  const ext = mode === "audio" ? ".mp3" : ".mp4";
  const safe = safeFileName(baseName || "media");
  return `${safe}${ext}`;
}

function extractMediaTitle(filePathOrBaseName) {
  const rawBaseName = path.basename(
    String(filePathOrBaseName || ""),
    path.extname(String(filePathOrBaseName || "")),
  );

  const withoutTag = rawBaseName.replace(/^\d+_/, "");
  const readable = withoutTag
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();

  return readable || "media";
}

module.exports = {
  runYtDlp,
  getYtDlpTitle,
  getYtDlpInfo,
  getDownloaderUserFacingError,
  getMediaType,
  normalizeMode,
  readableSize,
  makeOutputFileName,
  extractMediaTitle,
};
